# Generated by Django 3.0.7 on 2020-11-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(default='Unavailable', max_length=300),
        ),
    ]
